application: ietfvote
version: 2
runtime: python27
api_version: 1

threadsafe: false

default_expiration: "12h"

#builtins:
#- datastore_admin: on

libraries:
- name: django
  version: "1.2"

handlers:
- url: /favicon\.ico
  static_files: static/favicon.ico
  upload: favicon\.ico

- url: /robots\.txt
  static_files: static/robots.txt
  upload: static/robots.txt 

- url: /static
  static_dir: static 


- url: .*
  script: main.py

